apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/algambra-last/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
#    - name: sync.deployment.strategy.rollingUpdate.maxSurge  # Maximum additional pods during rollout
#      value: "1"
#   - name: sync.deployment.strategy.rollingUpdate.maxUnavailable  # Maximum unavailable pods during rollout
#      value: "1"

    automated:
      selfHeal: true
      prune: true
